# =========================================================
# ELMS - PRODUCTION PROPERTIES
# =========================================================

# =========================================================
# JPA
# =========================================================

spring.jpa.show-sql=false


# =========================================================
# LOGGING
# =========================================================

logging.level.root=WARN
logging.level.com.enterprise.lms=WARN
logging.level.com.lms.assessment=INFO


# =========================================================
# SWAGGER / API DOCUMENTATION
# =========================================================

springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false


# =========================================================
# REDIS
# =========================================================

spring.data.redis.ssl.enabled=true
