# =========================================================
# ELMS - STAGING PROPERTIES
# =========================================================

# =========================================================
# JPA
# =========================================================

spring.jpa.show-sql=false


# =========================================================
# LOGGING
# =========================================================

logging.level.root=INFO
logging.level.com.enterprise.lms=INFO
logging.level.com.lms.assessment=INFO


# =========================================================
# SWAGGER / API DOCUMENTATION
# =========================================================

springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true


# =========================================================
# REDIS
# =========================================================

spring.data.redis.ssl.enabled=true
